<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="beerExpert"
	targetNamespace="http://www.minh.jaxws/beerExpert/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.minh.jaxws/beerExpert/" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.minh.jaxws/beerExpert/"
				schemaLocation="../xsd/beerExpert.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getBeerAdviceRequest">
		<wsdl:part name="parameters" element="xsd:BeerExpertServiceRequest">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="getBeerAdviceResponse">
		<wsdl:part name="parameters" element="xsd:BeerExpertServiceResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="BeerExpertServicePortType">
		<wsdl:operation name="getBeerAdvice">
			<wsdl:input message="xsd:getBeerAdviceRequest"></wsdl:input>
			<wsdl:output message="xsd:getBeerAdviceResponse"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>	<wsdl:binding name="BeerExpertServiceBinding" type="xsd:BeerExpertServicePortType">

		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getBeerAdvice">

			<soap:operation soapAction="http://www.minh.jaxws/beerExpert/getBeerAdvice" />
			<wsdl:input>

				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BeerExpertService">
		<wsdl:port name="BeerExpertServicePort" binding="xsd:BeerExpertServiceBinding">
			<soap:address location="/service/beerExpertService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>